pub mod mail_parser;
pub mod auth_check;
pub mod url_extractor;
pub mod header_trace;
pub mod ioc_aggregator;
pub mod verdict;
pub mod mitre_mapper;
pub mod brand_impersonation;
pub mod content_heuristics;
